### ISSUE TITLE
Are bower dependecies auto-required

### ISSUE THREAD

**Issue by thomasdarde** [tenex/rails-assets#119]
When requiring a gem , the main part is included, but it seems the dependecies of the bower package are not.

Is this normal ?

**Comment by sheerun** [comment]
The main parts of dependencies should be included. Which gem are you talking about?

**Comment by thomasdarde** [comment]
I'm trying to use masonry:
https://github.com/desandro/masonry/blob/master/bower.json

Only the "main" part is included, but it's not working without the dependecies if I'm correct

**Comment by sheerun** [comment]
Yes, it seems dependencies are not included.

I'm not sure why. Maybe masonry has been builded against old versions of dependencies when they didn't have "main" entries yet.. or something else.

Thank you for noticing this.

**Comment by thomasdarde** [comment]
So it's their bower packaging which is not "up to date" ? I should ping @desandro ?

**Comment by sheerun** [comment]
No, it's rails-assets issue. I need to debug this. Please wait a while.

**Comment by thomasdarde** [comment]
Ok thanks a lot for the support ! Sorry for not investigating more but it's not really my field of expertise...

**Comment by sheerun** [comment]
OK, I was wrong. This is not rails-assets issue, it's a feature.

We don't want to include dependencies' manifests by default, because they can be broken, and they usually are. You as developer have full control over what you want to require and what not.

Manifests are only nice shortcuts so you don't need to know full paths.
