### ISSUE TITLE
rails-assets-jquery-mobile: CSS not included

### ISSUE THREAD

**Issue by frankie-loves-jesus** [tenex/rails-assets#147]
Hey everyone!

Similar to https://github.com/rails-assets/rails-assets/issues/146 -- how come rails-assets-jquery-mobile doesn't have any CSS files, only SCSS?

**Comment by sheerun** [comment]
We rename css files to scss. Why do you need css files?

**Comment by frankie-loves-jesus** [comment]
Sorry but I don't see the point of the rename? I mean, to a lot of people SASS is just an unnecessary layer of abstraction. If ones design is so complex one needs SASS, it's probably not that good in the first place.

Like the master said:

> Perfection is achieved, not when there's nothing left to add, but when there's nothing left to take away.

**Comment by sheerun** [comment]
SCSS is 100% compatible with CSS and it supports rails helpers like `image-url` etc.

We're converting files because you can include .scss file using `@include` statement in SCSS files and because we automatically convert all url() in css files to image-url font-url etc.

We cannot do this in pure .css. There are only two options: convert `.css` files to `.css.erb` and insert ugly `<% image_tag %>` helpers or convert them to `.scss` and change `url` to `image-url`. We've chosen latter option, because it's easier to implement and you gain `@include` feature.

**Comment by frankie-loves-jesus** [comment]
Hi!

Thanks for the response.

Is there a way to let the user choose? Maybe via `source 'https://css.rails-assets.org'` and `source 'https://sass.rails-assets.org'`?

Do we really need to `@include`, can't we just output all the CSS into one giant file?

Personally I'm a big fan of `.css.erb` and `<% image_tag %>` :)

**Comment by sheerun** [comment]
I'm afraid we can't afford it

**Comment by frankie-loves-jesus** [comment]
I would love to sponsor this development if possible.

**Comment by sheerun** [comment]
Unfortunately we can't do that with hosted service. 
It could be implemented in future as a rails_assets gem feature, though.

**Comment by pencilcheck** [comment]
The problem with including scss files are that there are multiple different preprocessor for it, so for example, in compass image-url takes 3 parameters while sass-rails takes one, so for those that utilize 3 parameters will get error when compiled via sass-rails and that's basically moot for us since the gem cannot be used. This is not a good design choice in my opinion.

Example:
https://github.com/rails-assets/rails-assets/issues/204

**Comment by sheerun** [comment]
Compass' docs say only one parameter is obligatory:
http://compass-style.org/reference/compass/helpers/urls/#image-url

**Comment by pencilcheck** [comment]
Yea, but when someone call `image-url(url, false, false)` it will be interpreted as error when you run with sass. Optional parameters doesn't mean they don't exist.

**Comment by sheerun** [comment]
Rails Assets uses only one-argument version, and doesn't require you to use `sass-rails` helpers. I don't see a problem.

**Comment by pencilcheck** [comment]
The problem is not whether Rails Assets uses the one or 3 arguments for image-url, is that different preprocessor engine has different helpers implemented, by including scss files this is basically asking asset pipeline to preprocess the file using whatever it is currently in the Gemfile, and in this case the preprocessor has a conflict because they have different arguments. So since my rails app uses sass-rails gem for .scss files, and the bower plugin uses compass, there is a conflict thus I can't include this into my app. So it would save everyone's time if Rails Assets would keep what they promise and include the file as included in bower.json instead of trying to be smart about it.

**Comment by sheerun** [comment]
It wouldn't save my time. What bower plugin are you talking about?

**Comment by pencilcheck** [comment]
I mentioned in my previous post, the carousel-slick bower plugin

**Comment by sheerun** [comment]
OK, I understand it now. `carouse-slick` uses `image-url($url, false, false)` as well as relative paths like `$slick-font-path: "./fonts/" !default;` so `.scss` file is unusable.

Rails Assets didn't generate this code. Rails Assets just changes `.css` extension to `.scss` and replaces `image` with `image-url` (still single argument). Original SCSS takes precedence over converted CSS file, so it's removed from package. It is a bug since original `.css` file should be converted to `.css.scss` file and you should be able to require it with `@import 'carousel-slick.css'`.

I created #206 for this bug.
