### ISSUE TITLE
angular-bootstrap does not work

### ISSUE THREAD

**Issue by tcwalther** [tenex/rails-assets#185]
The current angular-bootstrap component does not work. When including the file via

``` coffee
//= require angular-bootstrap
```

I get a "couldn't find file angular-bootstrap" error. I've looked at other issues here, and the usual problem seems to be that "main:" is not specified in the bower.json file of the package. However, it is specified here, although in an array syntax:

``` js
{
    "author": {
        "name": "https://github.com/angular-ui/bootstrap/graphs/contributors"
    },
    "name": "angular-bootstrap",
    "version": "0.11.2",
    "main": ["./ui-bootstrap-tpls.js"],
    "dependencies": {
        "angular": ">=1"
    }    
}
```

Can you look into that?

**Comment by sheerun** [comment]
Maybe you're using an old version of it. It works for me.

**Comment by tcwalther** [comment]
@sheerun it seems the bug is related to something entirely different, but I can't exactly reproduce it. After removing rails-assets and switching to plain bundler, then switching back because rails-assets is kinda nice, I could not even load angular, with the same error as above, and the same code that had worked before. After I did something else for 30 minutes, it miraculously started working.

I just hit into the same bug again after switching branches, and it seems it is somewhat related with Pow (http://pow.cx). If I use `lvh.me` instead, I get no errors on the asset pipeline, and rails-assets just works. Seems like pow possibly performs some weird caching... but this is just a vague assumption.

**Comment by aarongray** [comment]
I was having a similar issue, and realized that the normal version of angular-ui-bootstrap doesn't seem to packaged nicely for bower. Turns out, [angular-ui-bootstrap](https://github.com/angular-ui/bootstrap) has a [separate repo just for bower](https://github.com/angular-ui/bootstrap-bower). 

If you're having similar issues, try using the separate repo instead.

In your Gemfile:
`gem 'rails-assets-angular-ui-bootstrap-bower', '0.10.0'`

In app/assets/javascripts/application.js:
`//= require angular-ui-bootstrap-bower`
