### ISSUE TITLE
Convert .css file to .css.scss, not .scss

### ISSUE THREAD

**Issue by sheerun** [tenex/rails-assets#206]
To avoid overwriting of `.scss` files. It should solve issue mentioned in #147

**Comment by edwinv** [comment]
The commit solving this issue has a regression in compiling assets. The sass compiler by default will look for `file.scss` files when using `@import 'file'`. By changing the default extension to `.css.scss`, we are forced to write out the full path `file.css.scss` when requiring the file. Using `@import 'file.css'` will tell sass to not compile the file and keep the import statement in the CSS.

I think it is best to treat `scss` files as such and don't prepend the `.css` extension to them.

Just a side note: changing this behaviour in the asset gems causes unexpected behaviour in our custom compiler. Tracking down the cause of the issues was very hard, because suddenly the same gems have a different source. Maybe this kind of changes should only be made to new versions of gems instead of existing gems?

**Comment by sheerun** [comment]
I thought it won't matter..

**Comment by sheerun** [comment]
I'll try to think of solution soon. I think we'll need to rollback this change.. ping @teamon

**Comment by teamon** [comment]
Ouh :/. @sheerun Have you already deployed and rebuilt all gems with this change?

**Comment by sheerun** [comment]
Yes

**Comment by teamon** [comment]
Sh... I think we still need to rollback and rebuild if this is going to cause such issues.

Btw, I think we could include rails-assets git commit sha inside gems to track with what version of ra the gem was built.

**Comment by edwinv** [comment]
The gem as such is valid, because you write both the `@import` statement and change the file extensions. This is mainly an issue in when using a custom compile process, as we do for our product. We use the command line to compile the SASS files, therefore using `.scss` is easier. We have solved the issue by adding a check to see if the asset originates from a rails-assets gem.

Maybe it is worth checking how this issue is handled within Sprockets/Rails. Compiling assets with Sprockets is more used than our custom compile method :smile:

**Comment by aaronchi** [comment]
We are seeing errors like this with this change:

```
It's not clear which file to import for '@import "bootstrap-daterangepicker/daterangepicker-bs2"'. 
Candidates:
  bootstrap-daterangepicker/daterangepicker-bs2.css.scss
  bootstrap-daterangepicker/daterangepicker-bs2.scss

Please delete or rename all but one of these files.
```

**Comment by aaronchi** [comment]
@sheerun Why not just leave .css files as .css?

**Comment by futhr** [comment]
Hi I see same error as @aaronchi. Also suffix the files with `.css.scss` will clutter the logs with deprecation warnings from `sass` gem so that is a bad idea.

`DEPRECATION WARNING: Extra .css in SCSS file is unnecessary.`

**Comment by sheerun** [comment]
I think we're going back to generating only .scss files. Btw. there's followup in #230

**Comment by sheerun** [comment]
We yanked this change and started generating only `.scss` files again.

Please re-install all rails-assets gems to avoid inconsistencies.. It doesn't happen automatically.
