### ISSUE TITLE
Could not find gem 'rails-assets-readmore (>= 0) ruby' in rubygems repository https://rails-assets.org/.

### ISSUE THREAD

**Issue by mejackreed** [tenex/rails-assets#225]
I'm getting an error that previously did not exist when running `rails s` on a project.

Gemfile

``` ruby
gem 'rails-assets-leaflet-iiif', '~> 0.0.3', source: 'https://rails-assets.org'
gem 'rails-assets-readmore', source: 'https://rails-assets.org'
```

Running `bundle install` seems to work fine, it just seems to error when running rails commands

**Comment by sheerun** [comment]
Is it still happening? I cannot reproduce.

If it still happens, you create repository reproducing this issue?

**Comment by mejackreed** [comment]
Yes it is. I think we may be having the issue in that we are using rails-assets in an Rails engine. With the changes that happened (security issue) and not using a source block we seem to be having some strange things happen revolving around bundler and rails-assets. Removed rails-assets here: https://github.com/geoblacklight/geoblacklight/pull/282/files and will probably just hold off using unless we can specify `source` in a gemspec dependency.

**Comment by sheerun** [comment]
Well, I woudn't recommend using rails-assets for gems anyway.

Rails Assets seems good fit only for applications.

**Comment by mejackreed** [comment]
:+1: gotcha thanks!

**Comment by carpeliam** [comment]
I was running up against this in an app, with `rails-assets-angular`. With an empty Gemfile, it worked just fine- as it turned out, it was a bundler issue I ran into only when [configuring Bundler to use local gems](http://bundler.io/v1.8/bundle_config.html). After upgrading Bundler from 1.8.2 to 1.8.4, it worked (I'm guessing because of bundler/bundler#3450). So if anybody else runs in to this, try upgrading Bundler.

**Comment by mhuggins** [comment]
Upgrading bundler did the trick for me as well.  Was running on 1.8.3 previously.
