### ISSUE TITLE
How does rails-assets behaves with dipendences?

### ISSUE THREAD

**Issue by ProGM** [tenex/rails-assets#248]
My Gemfile is like this:

``` ruby
source 'https://rails-assets.org' do
  gem 'rails-assets-angular-isotope'
end
```

What should I require in my `application.js`? Only `angular-isotope` or also all it's dipendences?

Including only `angular-isotope` returns javascript errors at startup (like it's not including some...)

**Comment by sheerun** [comment]
They will be required as rubygems and available in Sprocket's load path, but you need to require each dependency individually. This is because bower packages often have invalid/extra dependencies set.

So the answer is:
1. Check on what `angular-isotope` depends on with `bundle list`
2. Add those dependencies in correct order in `application.js`
