### ISSUE TITLE
package name with capital letters causes error

### ISSUE THREAD

**Issue by ghost** [tenex/rails-assets#279]
I'm trying to install polymer and its components using rails-assets. This is part of my Gemfile: 

```
source 'https://rails-assets.org' do
  gem 'rails-assets-PolymerElements--iron-ajax'
end
```

After `bundle install` and running `rails server` it gives me

```
$ rails server
Could not find rails-assets-polymer--polymer-1.1.3 in any of the sources
Run `bundle install` to install missing gems.
```

Then I looked up into the `Gemfile.lock` and noticed following lines: 

```
    rails-assets-Polymer--polymer (1.1.3)
      rails-assets-webcomponentsjs (>= 0.7.2, < 0.8)
    rails-assets-PolymerElements--iron-ajax (1.0.4)
      rails-assets-Polymer--polymer (>= 1.0.0, < 2)
      rails-assets-polymerlabs--promise-polyfill (>= 1.0.0, < 2)
    rails-assets-polymer--polymer (1.1.3)
      rails-assets-webcomponentsjs (>= 0.7.2, < 0.8)
    rails-assets-polymerlabs--promise-polyfill (1.0.0)
      rails-assets-polymer--polymer (>= 1.0.0, < 2)
    rails-assets-webcomponentsjs (0.7.12)
```

The `rails-assets-PolymerElements--iron-ajax` package requires `rails-assets-Polymer--polymer` and the `rails-assets-polymerlabs--promise-polyfill` package requires `rails-assets-polymer--polymer`. These two maps to the same rails-assets package but the actual installed local package name is `rails-assets-Polymer--polymer`, so rails thinks that this package is not installed.

By now manually replacing the package name to the actual installed name in `Gemfile.lock` can fix this problem.

**Comment by monttda** [comment]
@gksu  the problem comes from bower files, since they have different root paths for the polymer dependency. 

[Polymer Iron-ajax](https://github.com/PolymerElements/iron-ajax) has on it's [bower file](https://github.com/PolymerLabs/promise-polyfill/blob/master/bower.json) the following (upcased Polymer)

```
"dependencies": {
    "promise-polyfill": "polymerlabs/promise-polyfill#^1.0.0",
    "polymer": "Polymer/polymer#^1.0.0"
}
```

while [Promise polyfill](https://github.com/PolymerLabs/promise-polyfill) has this  on it's [bower file](https://github.com/PolymerLabs/promise-polyfill/blob/master/bower.json) (downcased polymer)

```
"dependencies": {
    "polymer": "polymer/polymer#^1.0.0"
  }
```
