### ISSUE TITLE
SpinKit missing variables

### ISSUE THREAD

**Issue by halilim** [tenex/rails-assets#283]
Currently SpinKit [utilizes variables for customization](https://github.com/tobiasahlin/SpinKit/tree/1.2.2/scss). But the Rails Assets-installed one doesn't include _variables.scss and more interestingly, seems to have applied them instead.

**Comment by monttda** [comment]
@halilim  the problem comes from the [bower.js](https://github.com/tobiasahlin/SpinKit/blob/master/bower.json) of SpinKit since in it the only main specified is the .css and not the .scss thus Rails Assets is not using the scss files to create the gem but the .css ones that do not have the variables for customization
