### ISSUE TITLE
Cannot load fonts for font-awesome

### ISSUE THREAD

**Issue by ephracis** [tenex/rails-assets#286]
I have added the following to `Gemfile`:

```
source 'https://rails-assets.org' do
  gem 'rails-assets-bootstrap-sass'
  gem 'rails-assets-fontawesome'
end
```

Then added the following to `app/assets/stylesheets/application.css.scss`:

```
@import "bootstrap-sass";
@import "fontawesome";
```

It appears that the scss/css stuff is working correctly: bootstrap works fine and font-awesome apples the correct styles to my `span`. But the fonts are not loading. I get a 404 for `/fonts/fontawesome-webfont.woff2?v=4.4.0`. There's nothing in `public/assets` and `vendor/assets` contains no fonts. There are actuall no files matching "fontawesome" anywhere inside my application.

I am running in development environment, using Rails 4.2.4.

What have I missed?

**Comment by dudemcbacon** [comment]
Seconding this issue. I also can't figure out how to get the fonts to load. I can see them at `$GEM_HOME/gems/rails-assets-fontawesome-4.4.0/app/assets/fonts/fontawesome/fonts` but I'm not really sure how to load them. Similar to @ephracis, I've added rails-assets-fontawesome to my Gemfile and I've also added the following to `app/assets/stylesheets/application.css`:

```
/ *
 *= require_tree .
 *= require_self
 *= require fontawesome
*/
```

**Comment by monttda** [comment]
The guys from [Font Awesome](http://fontawesome.io/get-started/) got 2 supported gems of their toolkit, they got one in [SASS](https://github.com/FortAwesome/font-awesome-sass) and one in [LESS](https://github.com/FortAwesome/font-awesome-less).

So given that there are 2 existing gems that are supported by the creator of the toolkit I think It would be the best to use them instead of making a gem with rails assets. But if You would like to keep using rails assets I recommend You to check the solutions proposed in the issue #272
