### ISSUE TITLE
simplemde

### ISSUE THREAD

**Issue by hattwj** [tenex/rails-assets#287]
Both simplemde and NextStepWebs--simplemde-markdown-editor both require a different setting for the js to work:
//= require simplemde/simplemde.min.js

**Comment by monttda** [comment]
Could You give more details on this issue please like which setting wasn't working for you

**Comment by hvenables** [comment]
Tried to use rails assets to load simplemde as well however it did not work.

Their was an error requiring codemirror but it seems that this error came from the fact the the bundle version of the gem did not contain the min version of the files.

https://github.com/NextStepWebs/simplemde-markdown-editor/tree/master/dist

**Comment by hut8** [comment]
@hvenables what files is it missing? What error are you getting? I need more information to debug this. It seems odd that a tool would mandate that the minified files are used.

**Comment by eloyesp** [comment]
@hut8 @monttda I can give more details... the issue is that javascript file available is [this one](https://github.com/NextStepWebs/simplemde-markdown-editor/blob/master/src/js/simplemde.js) that uses `require` (as it uses browserify to build).

On the other hand, the scss file does not have the extension `css.scss` (but I'm not sure if that can be an issue).

I think that the best option, would be to make available the files in the [debug folder](https://github.com/NextStepWebs/simplemde-markdown-editor/tree/master/debug), but I'm not sure if that is possible as I'm not sure how rails-assets build the gems.

Thanks for making this possible.

**Comment by veelenga** [comment]
I also faced with this issue following [this](https://rails-assets.org/#/components/simplemde) instructions. Error within console:

```js
Uncaught ReferenceError: require is not defined
    at simplemde.self-638d724….js?body=1:4
    at simplemde.self-638d724….js?body=1:4
(anonymous) @ simplemde.self-638d724….js?body=1:4
simplemde.self-638d724….js?body=1:1379 Uncaught TypeError: this.render is not a function
    at new SimpleMDE (simplemde.self-638d724….js?body=1:1379)
    at <anonymous>:7:1
    at n.t.SnapshotRenderer.n.assignNewBody (turbolinks.self-c5acd7a….js?body=1:6)
    at n.t.SnapshotRenderer.n.replaceBody (turbolinks.self-c5acd7a….js?body=1:6)
    at turbolinks.self-c5acd7a….js?body=1:6
    at n.t.Renderer.t.renderView (turbolinks.self-c5acd7a….js?body=1:6)
    at n.t.SnapshotRenderer.n.render (turbolinks.self-c5acd7a….js?body=1:6)
    at Function.t.Renderer.t.render (turbolinks.self-c5acd7a….js?body=1:6)
    at e.t.View.e.renderSnapshot (turbolinks.self-c5acd7a….js?body=1:6)
    at e.t.View.e.render (turbolinks.self-c5acd7a….js?body=1:6)
```

**Comment by joshjordan** [comment]
This looks like trouble in the `simplemde` code. The rails-assets gem appears to be loading and getting served up properly. You're going to have to take that up with the simplemde folks. Sorry we can't be more helpful!
