### ISSUE TITLE
pdfjs-dist doesn't have all the files in package

### ISSUE THREAD

**Issue by laginha87** [tenex/rails-assets#288]
Hi
The package https://github.com/mozilla/pdfjs-dist/tree/master has js files that are in the web/ folder that are not copied over to the rails-assets-pdfjs-dist gem.
Is there a way to include them?
Thanks.

**Comment by monttda** [comment]
Hello 

You would have to make a change in the directories order of pdfjs-dist because when Rails assets  receives a bower.json which has a main for an X type of asset (in this case a javascript) it will only take the files with that X extension(.js in this case)  that are in the same folder or a subfolder in which the main asset is located. So for this case the main files for javascript assets are in the build folder and since the web folder is not inside the build folder any javascript file there will be ignored.

So the only way would be if someone would change the structure of the pdfjs-dist repository or remove the main files from the bower.json.
