### ISSUE TITLE
How to manage missing "main" in bower.json?

### ISSUE THREAD

**Issue by teamon** [tenex/rails-assets#3]

**Comment by teamon** [comment]
IDEA: Use github API to create Issues in github repos

**Comment by sheerun** [comment]
Idea ++, but I'd include in such PR all issues. e.g. missing description, component.js -> bower.js, etc.

**Comment by porada** [comment]
Basically, what @sheerun described is a Bower package validator. It may be a good idea, but this surely is a separate project to build (unless there exists a similar one).

**Comment by sheerun** [comment]
I think `main` should not be obligatory. `component.json` can contain such field as `ignore` and deliberately not have `main` key, because of character of library. Here are examples: zurb-foundation, bootstrap, each pure sass/scss/less colleciton like preboot, html-polyfills, dexteryy/mo, jquery-ui, and every time you need just one js from repo, and not huge compiled script.

If `main` exists in mainifest, we can create shortcut for including script (like `#= require selectize` instead of `#= require selectize/selectize` or worse). I think this feature is enough for developers to issue pull requests on repositories that should contain `main` key in `component.json`.

All to all, here is how imo component conversion should work:
1. Filter out scripts from repo (preserve directory structure); ignore files defined under `ignore` key in `component.json`; place them in `vendor/javascripts/COMPONENT_NAME/` directory
2. Do the same for stylesheets, images, and fonts.
3. Discover main js file, and place it under `vendor/javascripts/COMPONENT_NAME.js`
4. Do the same for main stylesheet and place it under `vendor/stylesheets/COMPONENT_NAME.css`

That way _each_ bower repository can be converted to Gem, and used in following way:
1. If component has main js/css, then just `#= require foobar`
2. Regardless if component has main js/css, you can include any js/css from repo by `#= require foobar/PATH`. For example if language files are available in `foobar` repository under `lang/en.js`, then you can include them in following way: `#= require foobar/lang/en.js`.

It's important to realize `component.json` can explicitly define ignored files.

@teamon @porada @jandudulski @chytreg

**Comment by sheerun** [comment]
Implemented in #33
