### ISSUE TITLE
No build error but gem not created

### ISSUE THREAD

**Issue by xire28** [tenex/rails-assets#319]
The following gem is a dependency for `xire28--behavior-google-map-info-window-ujs` but the build process seems to have failed without issuing any error.

I get this message when updating using bundler: 

```
Gem::RemoteFetcher::FetchError: bad response Not Found 404 (https://rails-assets.org/gems/rails-assets-behavior-google-map-marker-ujs-1.0.2.gem)
An error occurred while installing rails-assets-behavior-google-map-marker-ujs
(1.0.2), and Bundler cannot continue.
Make sure that `gem install rails-assets-behavior-google-map-marker-ujs -v
'1.0.2'` succeeds before bundling.
```

I tried to create a new release (tag v1.0.3) but I got the same result.

When I added the component on his own and got an other gem (issue #318) : `rails-assets-xire28--behavior-google-map-marker-ujs` and it worked.

Not sure why it failed, could you have a look at it or simply delete the gem ?

**Comment by jaybloke** [comment]
I have a similar problem when trying to install a gem... I've tried rebuilding but no success:

```
Gem::RemoteFetcher::FetchError: bad response Not Found 404 (https://rails-assets.org/gems/rails-assets-angular-cookies-1.5.3.gem)
An error occurred while installing rails-assets-angular-cookies (1.5.3), and Bundler cannot continue.
Make sure that `gem install rails-assets-angular-cookies -v '1.5.3'` succeeds before bundling.
```

**Comment by hut8** [comment]
I'm looking into this tonight.

**Comment by hut8** [comment]
I apologize for this. The change of hosting providers was not quite seamless :wink:

Because of a tight time frame with ShellyCloud closing, I ended up temporarily deploying rails-assets.org to a hosting provider other than Digital Ocean, but just a few minutes ago I flipped the switch and now everything is pointed at one of Digital Ocean's data centers. In my panic to get the infrastructure set up, I forgot one symlink which caused your gems to get built correctly and then put in entirely the wrong place :boom: Of course, I fixed this in the process of moving the servers to DO.

It should be resolved now. These work for me:
- https://rails-assets.org/gems/rails-assets-angular-cookies-1.5.3.gem 
- https://rails-assets.org/gems/rails-assets-behavior-google-map-marker-ujs-1.0.2.gem

Please let me know if you continue to have issues. Thanks for your patience.

**Comment by xire28** [comment]
Thanks !

**Comment by xire28** [comment]
Sorry to bother you again but I didn't notice some of my other gems have the same issue:
-  `rails-assets-xire28--behavior-google-map-info-window-ujs`
-  `rails-assets-xire28--behavior-google-map-rectangle-ujs`
-  `rails-assets-xire28--behavior-google-map-circle-ujs`
-  `rails-assets-xire28--behavior-google-map-polygon-ujs`
-  `rails-assets-xire28--behavior-google-map-polyline-ujs`

It wasn't an ideal time to import all of my packages :laughing:. Could you do something about them too ?

Thank you for your time !

**Comment by hut8** [comment]
They will be done momentarily. They are in the build queue.

**Comment by xire28** [comment]
Thank you

**Comment by jaybloke** [comment]
Thanks @hut8
