### ISSUE TITLE
Question: using rails-assets in gems

### ISSUE THREAD

**Issue by anitagraham** [tenex/rails-assets#327]
Hi,
I have begun using rails-assets in my application. :+1:
Now I've added it to a gem which is used in the application, but the assets are not being found.

In the gem's Gemfile:

``` ruby
source 'https://rails-assets.org' do
  gem 'rails-assets-multiselect'
end
```

In the application's Gemfile:

``` ruby
gem 'mygem'
```

In the logfile when starting the application

``` text
 ActionView::Template::Error (File to import not found or unreadable: multiselect.
Load paths:
```

The load paths include the rails-assets paths for the assets in the application's Gemfile, but not the loadpath for `multiselect`.

Can I use rails-assets in this way. Is there more I need to do?

thanks

**Comment by hut8** [comment]
I will get to this probably Monday because I'm swamped with work this weekend. But I'm somewhat confused, as it seems like normally in a gem you would have a gemspec, and the actual Gemfile would have one line that just contains the word `gemspec`. I didn't think it was usual to have a Gemfile inside a gem that actually listed metadata which would be redundant with that in the gemspec.

**Comment by hut8** [comment]
Closing due to lack of feedback
