### ISSUE TITLE
slick-carousel/slick.scss is imported twice

### ISSUE THREAD

**Issue by shobee** [tenex/rails-assets#352]
Hi there,

`rails-assets-slick-carousel-1.6.0/app/assets/stylesheets/slick-carousel.scss` looks like this:

``` ruby
@import 'slick-carousel/slick.scss';
@import 'slick-carousel/slick.scss';
```

Not sure if this is the right place to address this and where this can be fixed?

**Comment by hut8** [comment]
Interesting. I will look into this tomorrow; I have some pretty urgent other stuff right now. Is this causing issues?

**Comment by hut8** [comment]
Alright I lied; I'll look into it today.

I believe there's a bug here: https://github.com/tenex/rails-assets/blob/master/app/models/build/transformer.rb#L96

It's caused by the fact that slick-carousel includes css, scss and less. That's highly unusual. The css ends up being renamed to scss, and :boom: duplicate entries.

**Comment by hut8** [comment]
OK more information :smile: 

Reading the bower spec, specifically the history behind [this pull request](https://github.com/bower/spec/pull/43), I think that the `slick-carousel` folks have a bug in their `bower.json`. Specifically, I don't think they should be including slick.css in `main`. On a totally unrelated note, because of https://github.com/bower/bower/pull/2232, they don't need to be including 
the `version` tag either if you're planning on making a PR to that repo :smirk: 

https://github.com/twbs/bootstrap/pull/16359/files -- looks like in 2015, Bootstrap removed the regular `.css` file and just includes `.less` in `main`. So I think that slick-carousel should follow suit. What are your thoughts on this?

**Comment by shobee** [comment]
Thanks for diving into this so quickly! I think it is obviously which way to go. So I am going to close this issue here and open a new at the `slick-carousel` repository.
