### ISSUE TITLE
imagesLoaded is not a function

### ISSUE THREAD

**Issue by dt1973** [tenex/rails-assets#357]
Hi! Having problems with imagesLoaded (https://github.com/desandro/imagesloaded/) and Rails Assets:

http://code.runnable.com/V1Pdn9JeGy0HpJed/imagesloaded-bug-test-for-ruby-on-rails (keep reloading if Runnable acts up)

```
Uncaught TypeError: Cannot read property 'prototype' of undefined -- imagesloaded.js:116
Uncaught TypeError: $(...).imagesLoaded is not a function -- application.js?body=1:20 
```

**application.js**:

```
//= require imagesloaded
```

Same setup works http://jsbin.com/ravewucodo/edit?html,js,console,output in plain mode.

P.S. Also posted in https://github.com/desandro/imagesloaded/issues/

**Comment by hut8** [comment]
I'll investigate in a few minutes

**Comment by dt1973** [comment]
Thanks @hut8!

**Comment by hut8** [comment]
First, never do this:

```
source 'https://rails-assets.org'
gem 'rails-assets-imagesloaded'
```

Instead, use the block form:

```
source 'https://rails-assets.org' do
    gem 'rails-assets-imagesloaded'
end
```

But that's unrelated to the issue (that's a security problem, since it will then try to load other gems from rails-assets.org).

This is the line that's causing an error:

```
ImagesLoaded.prototype = Object.create( EvEmitter.prototype );
```

In the test file from that repo, there's [this line](https://github.com/desandro/imagesloaded/blob/master/test/index.html#L11) that seems to probably load that file. Maybe you should load ev-emitter first.

**Comment by dt1973** [comment]
Thanks for the note about the block, but it doesn't seem to be working with Runnable's old version of Rails.

As for ev-emitter, it worked, thanks!
