### ISSUE TITLE
Unbrowserified assets

### ISSUE THREAD

**Issue by jonatanklosko** [tenex/rails-assets#367]
We use [Simple Markdown Editor](https://github.com/NextStepWebs/simplemde-markdown-editor) in our Rails project via _rails-assets.org_ and it works very well. The problem emerged when I've tried to update the gem, the editor didn't work and I got JS error in the console (`ReferenceError: require is not defined`). Using browser tools I saw that indeed there's `require` call in the library's file. Then I checked the previous version (that works) and the same file was compiled and minimified. So I started searching for the change in the SimpleMDE's repository which caused the difference.
The only one I consider to be related is the [`"main"` attribute in the `bower.json`](https://github.com/NextStepWebs/simplemde-markdown-editor/blob/master/bower.json#L9).
Before it was: `"main": ["dist/simplemde.min.js", "dist/simplemde.min.css"],`
(browserified and minimified)
Now it is: `"main": ["src/js/simplemde.js", "src/css/simplemde.css"],`
(just the source code with `require` in particular).

Summary the library doesn't work as a Ruby gem from _rails-assets.org_ at the moment so I guess there's something wrong with the build process.

**Comment by hut8** [comment]
There is something wrong with the build process, but not the gemification that is done by rails-assets.org. It sounds like they stopped using something like browserify to actually build the javascript library. Confusingly (to me), Bower recommends _against_ including minified or "built" (e.g., "browserified") JS. So it sounds like simplemde is actually moving in the right direction as recommended by bower. However, many (if not most) packages continue to include the "built" version of the code in `main`, since otherwise you have to direct the user to run an external tool (which could be anything from browserify to systemjs to webpack to whichever front-end build system happens to be popular today).

Have you filed an issue with simplemde? What would you like to see happen?

**Comment by jonatanklosko** [comment]
I've created an issue in the SimpleMDE's repository before, see: NextStepWebs/simplemde-markdown-editor/issues/407.
Maybe _rails-assets.org_ should look for a `dist` directory and use it if it's present?

**Comment by jonatanklosko** [comment]
The referenced issue is exactly the same thing.
Any thoughts here?

**Comment by vlymar** [comment]
I'm currently experiencing the same exact issue when trying to pull https://github.com/cure53/DOMPurify into our Rails app. rails-assets is bundling the `src/` files, not the `dist/` files.

The src files require "browserification" so basically the js code blows up at runtime.

> Confusingly (to me), Bower recommends against including minified or "built" (e.g., "browserified") JS. 

I found [this conversation](https://github.com/bower/bower/issues/368#issuecomment-15916138) in the bower repo that seems to support that statement, though there is definitely some disagreement there.

Correct me if I'm wrong, but rails-assets depends on bower components having "built" components packaged within them, because end users are supposed to just be able to bundle the gem and require the asset and have the prod version of the asset automatically included.

If rails-assets depends on `bower.json`'s `main` directive, and the convention is to start using `src` files for the main directive, what we're gonna see is modern javascript libraries are going to stop working with the traditional rails-assets workflow, which is unfortunate.

Out of curiosity, has there been any discussion about alternatives to `bower.json`'s `main` for choosing which files to bundle? One possible (subpar) option would be to automatically include all files under `dist/` in the gem, under `assets/javascripts`, but not automatically require them.

This leaves the option to the developer to do something like:
`//= require your-dependency/dist/built-dependency`
 I don't know enough about rails-assets or bower to really understand the implications of this though.

I'm pretty new to the JS tooling ecosystem, so I may have made a number of bad assumptions here. I don't envy the situation the rails-assets devs are in - this is a complicated situation. My company depends heavily on rails-assets, and it has "just worked" quite well for all this time. We greatly appreciate all the work that has gone into this tool.

I'm not expecting any immediate change to come from this comment, just want to resurrect this discussion since I'm anticipating others will have similar experiences in the future.

**Comment by joshjordan** [comment]
Thanks for the thoughtful post, @vlymar!

**tldr:**
**1. Short-term: fork it, build it, commit it, and add your fork to rails-assets** 
**2. Long-term: would love to see a PR in this direction!**

> Correct me if I'm wrong, but rails-assets depends on bower components having "built" components packaged within them, because end users are supposed to just be able to bundle the gem and require the asset and have the prod version of the asset automatically included.

You are not wrong - that is exactly how it is intended to work.

> If rails-assets depends on bower.json's main directive, and the convention is to start using src files for the main directive, what we're gonna see is modern javascript libraries are going to stop working with the traditional rails-assets workflow, which is unfortunate.

You are correct there as well, and that is unfortunate. The guidance from our side so far has been:

1. Try to convince the maintainer to include built assets in the repo.
2. Fork it and commit built assets yourself.

Of course, for the former solution, the maintainer has to be willing (and probability of willingess goes down if Bower provides alternate guidance). For the latter, that gem is likely to never get updated with new releases from the primary repo.

> Out of curiosity, has there been any discussion about alternatives to bower.json's main for choosing which files to bundle? One possible (subpar) option would be to automatically include all files under dist/ in the gem, under assets/javascripts, but not automatically require them.

Yeah, we have discussed a few solutions. We discussed crowdsourcing a list of bower libs that don't have built assets and displaying a warning, but I don't believe we can really get enough participation to make it useful. We discussed attempting to figure out the build command run it, but that's error prone and presents arbitrary code execution issues. 

I like the solution you've proposed. `src` directories are usually awash with too many files to reasonably require, but `dist` directories are not. Would you be willing to work on this? I am happy to provide guidance.
