### ISSUE TITLE
bower component won't compile specific version https://github.com/zellerda/Tokenize

### ISSUE THREAD

**Issue by lifeiscontent** [tenex/rails-assets#368]
any reason why the 2.6 version of this component won't compile on rails-assets?

**Comment by hut8** [comment]
What error message are you getting? What do you mean compile exactly?

**Comment by hut8** [comment]
I'm investigating now:
- https://rails-assets.org/status indicates there was no failure in building anything related to this. 
- https://github.com/zellerda/Tokenize does indicate that the latest version is 2.6, as you point out.
- Updates from Sidekiq seem to be operating normally. Everything looks kosher there.
- https://rails-assets.org/#/components/zellerda--Tokenize indicates that the latest version is 2.5.2
- https://bower.io/search/ makes it look like Tokenize was removed from the registry, since rails-assets has it and bower doesn't anymore.
- Note on https://github.com/zellerda/Tokenize indicates that this repository isn't updated anymore.

So, it looks like the author of the library removed it from Bower, and you should probably use Tokenize2 instead. If you really want that old, unmaintained version, you can either ask the author to re-add it to Bower somehow or alternatively you could take that upon yourself. Hope this has been helpful! Feel free to re-open if you have further issues with this.
