### ISSUE TITLE
couldn't find file 'react-router' with type 'application/javascript'

### ISSUE THREAD

**Issue by rvan1** [tenex/rails-assets#371]
I'm trying to use a 'react-forms-example' with this in the Gemfile:

```
source 'https://rails-assets.org' do
  gem 'rails-assets-classnames'
  gem 'rails-assets-lodash'
  gem 'rails-assets-react-router'
```

As well as this in application.js:

```
//= require lodash
//= require react
//= require react-router
//= require classnames
//= require router/variables
//= require_tree ./stores
```

But I get this error:

```
Sprockets::FileNotFound in React#show
...
couldn't find file 'react-router' with type 'application/javascript'
Checked in these paths: 
  /home/bvan/ror/react-forms/app/assets/images
  /home/bvan/ror/react-forms/app/assets/javascripts
...

Would I be better off using more ordinary asset gems for this?
```

**Comment by joshjordan** [comment]
Unfortunately, this package is incomplete. Its `bower.json` file does not include a `main` which tells us which javascript file to use. That's why you see this error on its [rails-assets page](https://therac25.rails-assets.org/#/components/react-router):

![image](https://cloud.githubusercontent.com/assets/521674/17460966/ab930506-5c49-11e6-8c0a-d281aad51b42.png)

While all the files in the package are listed and you could theoretically `require` (or better yet, `require_tree`) them, I suggest you [contact the maintainers](https://github.com/rackt/react-router) and ask them to include a `main` in their `bower.json`. More guidance on that can be found in the [bower.json spec](https://github.com/bower/spec/blob/master/json.md#main). You could also fork it, send them a PR, and then put your fork into bower for use with Rails Assets.

**Comment by rvan1** [comment]
I don't find a 'bower' file in either of these projects. Since I just want to run the example forms app, I could require the files but don't know where the list is; except for about 38 files in 'modules'. I tried require_tree ./react-router, but needs to be a directory. I don't know how rails asset pipeline/sprockets works but know that I don't actually find the 3rd party files anywhere like 'vendor/assets'. I'm guessing they are pulled directly from gems during compile, so never really exist in the project.
