### ISSUE TITLE
HTTP 404 when bundling

### ISSUE THREAD

**Issue by douglaslise** [tenex/rails-assets#395]
I am always getting this error when bundling with gems from rails-assets, but in the end the gems are installed normally and bundle succeeds. Should I ignore this error or are there some config that I could change?
```
$ bundle -V
Running `bundle install --verbose` with bundler 1.14.5
Found changes from the lockfile, re-resolving dependencies because the dependencies in your gemfile changed
HTTP GET https://rails-assets.org/versions
HTTP 404 Not Found https://rails-assets.org/versions
Bundler::Fetcher::FallbackError: Net::HTTPNotFound
/home/douglas/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.5/lib/bundler/fetcher/downloader.rb:34:in `fetch'
  /home/douglas/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.5/lib/bundler/fetcher/compact_index.rb:116:in `call'
  /home/douglas/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.5/lib/bundler/compact_index_client/updater.rb:43:in `block in update'
```

**Comment by hut8** [comment]
This is caused by https://github.com/tenex/rails-assets/issues/332, which has information about the new `versions` API endpoint. Pull requests are welcome for support, which I have already started on this branch (but will not have time to finish it any time soon): https://github.com/tenex/rails-assets/tree/hut8/support-new-index

**Comment by douglaslise** [comment]
OK, thank you by the answer. I know very little how a rubygems server work, but if possible I would study and try to help.
I discover this project recently, and I found that it is very helpful for my projects.
Great work.
