### ISSUE TITLE
Too many slicks

### ISSUE THREAD

**Issue by dsandstrom** [tenex/rails-assets#399]
There are at least three somewhat identical gems that pull in https://github.com/kenwheeler/slick.  Moreover, one is broken.

Broken: https://rails-assets.org/#/components/slick.js
When you specify slick.js in your javascript assets file, it pulls in a css file.  I assume because the css is erroneously named slick.js.css.

Seems to be working: https://rails-assets.org/#/components/slick-carousel
Although, slick-carousel needs to be required after jquery unlike the instructions demonstrate.

Untested: https://rails-assets.org/#/components/kenwheeler--slick
Looks identical to the others.

**Comment by dsandstrom** [comment]
I was able to get the js file to work for slick.js by using `require slick.js.js`, but not sure how to require the css file.  I tried `slick.js`, `slick.js.css`, `slick.js.scss`, and `slick`.  Going to stick with slick-carousel package.

**Comment by hut8** [comment]
Is this the same as https://github.com/tenex/rails-assets/issues/361 ?

**Comment by dsandstrom** [comment]
It's similar, but there seems to be a problem with duplicate gems.  That issue may explain how to get slick.js working, but it doesn't seem worth the effort when we have 2 others to pick from.

**Comment by hut8** [comment]
When you say it's similar, how is it different?

Also, we're pulling bower information directly from the bower registry. So (unless you find differently), those are probably all listed in Bower as separate packages. That would be an issue to take up with the maintainer(s) of Bower, since it's risky for us to selectively determine which is the "best" bower package that references the same repo. Does that make sense?

**Comment by dsandstrom** [comment]
Sorry, didn't realize that the problem resides with bower.  I'll close this.
