### ISSUE TITLE
Certificate Expired Again

### ISSUE THREAD

**Issue by jimmyhmiller** [tenex/rails-assets#419]
Seems to be a reoccuring issue. Is there anything that can be done to stop this from happening again?

**Comment by aleatham** [comment]
clogged up deploy pipeline :(

**Comment by Sirius238** [comment]
@jimmyhmiller someone suggest this before:

Put certbot in cron and this can just not happen.
https://certbot.eff.org

source(https://github.com/tenex/rails-assets/issues/416)

The issue is stopping me from deploying to Heroku.
But in case you just want to update or install a gem locally I found this workaround:

bundle config mirror.https://rails-assets.org/ http://insecure.rails-assets.org/

Once they updated their certificate you can delete the mirror again.
Unfortunately I cannot set this up on the heroku server :-/

**Comment by IngusSkaistkalns** [comment]
😢

**Comment by eiwi1101** [comment]
Following @RaykPlatzek's solution, if you're using a `source` block in a Gemfile, you can (temporarily) change your source to the insecure server to unclog your pipes:

```ruby
# HACK - Rails Assets cert expired, see
# https://github.com/tenex/rails-assets/issues/419
source 'http://insecure.rails-assets.org/' do
  # gems
end
```

Heroku etc should* pick up on it without having to configure a mirror on your build servers.

**Comment by irfanfadilah** [comment]
*Waiting Patiently*

**Comment by Sirius238** [comment]
@eiwi1101  I tried 

```
source "http://insecure.rails-assets.org/" do 
    .... 
end

```
in my gemfile but for some reason when running e.g. `bundle update` it will still try to access 
https://rails-assets.org/ hence I had to create the mirror for bundle.

**Comment by JulienCorb** [comment]
be careful: to use: `source "http://insecure.rails-assets.org/" do  ` isn't very secure. 

The Rails world is waiting for the SSL cert renewal...

**Comment by wintersolutions** [comment]
Hi. For people that want to run `bundler install` etc. without changing the `source` in `Gemfile` I found this quick workaround:

http://albertech.blogspot.de/2016/11/get-past-ruby-error-could-not-verify.html

Just remember to delete the line from `.gemrc` when the cert is up to date again.

**Comment by Sirius238** [comment]
It seems to be working again :-) 

Thanks for updating the certificate.

**Comment by felixbuenemann** [comment]
If the Let's Encrypt cron jobs for renewal are installed, it's probably missing a reload hook, so nginx loads the new certificate after a renew.

This line in `/etc/letsencrypt/cli.ini` should fix it:

```
post-hook = /usr/sbin/nginx -s reload
```
