### ISSUE TITLE
Error when require vvvmax--unitegallery

### ISSUE THREAD

**Issue by marciojg** [tenex/rails-assets#423]
Hi, @tenex and @joshjordan 

You are can change the require of [unitegallery](https://rails-assets.org/#/components/vvvmax--unitegallery) component ?

Now is `//= require vvvmax--unitegallery` but the correct is `//= require unitegallery`

Thanks,

**Comment by pedrofurtado** [comment]
@marcioJesus 

I added a component in Rails Assets website with the correct name ("unitegallery"). Please, check it out: https://rails-assets.org/#/components/unitegallery

Now you can require this library with something like this:

```javascript
// app/assets/javascripts/application.js

/**
 *= require unitegallery
 */
```

**Comment by pedrofurtado** [comment]
@marcioJesus But be aware of fact that Rails Assets may not have all files from original repository (https://github.com/vvvmax/unitegallery), because it is only loaded the files declared in "main" bower.json directive. 

Here you can check the main files of this library: https://github.com/vvvmax/unitegallery/blob/master/bower.json#L7-L9
