### ISSUE TITLE
Better forks system

### ISSUE THREAD

**Issue by jnylen** [tenex/rails-assets#44]
Hi,
It would be better if there was some kind of way to match forks to the main repo.
And a way to see a list of them on the main one. For example when the old version stops being maintained and taken over by another user it should be possible to find this gem easily in the same list.

**Comment by joshjordan** [comment]
Interesting. Can you give me some examples of forked components, and what you'd like to see for them? Thanks for taking the time, @jnylen

**Comment by jnylen** [comment]
Here are some:
- Angular2 is just Angular if possible it should just point to one name (maybe aliases kinda? for legacy rails-assets)
- [sweetalert](https://github.com/t4t5/sweetalert) and [sweetalert2](https://github.com/limonte/sweetalert2) are forks

I think it should be possible to grab "fork of" via github's API on creation and just mark it as a fork.
Think alternativeto.

And if possible it would be amazing to show "this one is updated more recently" in the list aswell.

**Comment by joshjordan** [comment]
That's wonderful. Do you know of any structured data that tells us which
things are forks of others? Obviously github is one source of information
on this, but it would be ideal if bower or npm published this as "official
forks" or such. Any insights?

**Comment by jnylen** [comment]
Hi Josh,
https://developer.github.com/v3/repos/forks/ to get forks from each repo
and use https://api.github.com/repos/username/reponame

To get "Primary repo" which is the one it's forked from.

**Comment by hut8** [comment]
@joshjordan My opinion is that this is somewhat risky since "forks" mean a lot of things in different contexts. The two examples given by @jnylen illustrate this. With the angular example:

https://rails-assets.org/#/components/angular
https://rails-assets.org/#/components/angular2

These aren't actually forks at all, in fact, they actually point to the same Git repo! They're identical clones except for the name, versions and all.

The other case, sweetalert and sweetalert2 is more compelling, but sweetalert2 is actually both ahead and behind sweetalert. It seems like a large number of forks out there are actually just organization-specific (poorly architected) customizations of the "original" repo. This seems like it would be pretty misleading to point to the "new thing" based solely on commits ahead and behind.

If you agree, feel free to close.

**Comment by joshjordan** [comment]
I do agree. I also don't want to bake in github-specific functionality. Let's stick to data provided by bower.
