### ISSUE TITLE
Reminder: Renew rails-assets.org certificate

### ISSUE THREAD

**Issue by justinhoward** [tenex/rails-assets#457]
Reminder that the certificate expires this Friday September 27.

**Comment by summera** [comment]
Certificate expired 😢

**Comment by skyschub** [comment]
@joshjordan I am very disappointed in the light of the conversation in https://github.com/tenex/rails-assets/issues/445#issuecomment-497334900, and the fact that, once again, the certificate is expired, breaking production setups. With all due respect, this is a bad joke.

**Comment by angusluk** [comment]
expired again. please renew it, and make it a automation process

**Comment by joshjordan** [comment]
@denschub apologies. The root cause has still not been found. The previous renewal went off without an issue and this one did not. It appears to be related to open file handles that cause nginx to sometimes not see the new cert. For what its worth, I did honor our agreement and implement the solution we discussed back on May 30:

![image](https://user-images.githubusercontent.com/521674/65815587-85b8e180-e1bf-11e9-90a9-d32edada7d82.png)

However, there appears to be more to do. Not much to be done in this case except keep hunting down failure cases. For what its worth, rails assets production machines have seen a number of file-handle related bugs as it thrashes the file system at a relatively high rate pulling in/blowing away components and building gems.

@angusluk I understand that you're not following the conversation. Automation is failing.

This has been fixed as of about 10 minutes ago. To provide some context, Rails Assets is on track to be hard down for about 1.5 hours total this year, or an uptime of 99.9998%. We have been soft down for about 12 hours this year, or an uptime of 99.998% with a simple workaround for the SSL cert issue we're having. Working on it, folks.
