### ISSUE TITLE
rails-assets.org  server is down

### ISSUE THREAD

**Issue by shodhangk** [tenex/rails-assets#468]
Please resolve as soon as possible.

rails-assets.org’s server IP address could not be found.

**Comment by joshjordan** [comment]
On it.

**Comment by joshjordan** [comment]
We are waiting for a nameserver update to resolve this.

**Comment by joshjordan** [comment]
And still waiting. We've updated our registrar to point directly at Digital Ocean DNS rather than going through our fallback automation. DigitalOcean DNS is working properly (verify with `dig @ns1.digitalocean.com rails-assets.org`). We're just waiting for the registrar to propagate the nameserver change, which we have unfortunately little insight into.

For those of you who are stuck and need immediate resolution, you can override the DNS locally with two steps:
1. Add an `/etc/hosts` entry for `192.241.135.61 insecure.rails-assets.org`
2. Change your Gemfile source from `https://rails-assets.org` to `http://insecure.rails-assets.org`

Will be monitoring for propagation.
