### ISSUE TITLE
ssl verification is failing for https://rails-assets.org

### ISSUE THREAD

**Issue by danmoore2205** [tenex/rails-assets#470]
Hello, 

I'm getting the following error when i bundle install
```
Retrying fetcher due to error (2/4): Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for https://rails-assets.org/.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
```

Gemfile: 

```
group :production do
  gem 'rails-assets-airbrake-js-client', source: 'https://rails-assets.org'
end
```

Also when i visit https://rails-assets.org/ in my browser it complains the connection is not private.

Any help appreciated.

Thanks

**Comment by timothyrobb** [comment]
The SSL cert has been invalid for the past hour and 10min as of the time of this message.
As discussed here: https://github.com/tenex/rails-assets/issues/416#issuecomment-349184372
You can either set it to an insecure route if it's an emergency, otherwise it's best to wait for the SSL cert to be renewed rather than opening yourself up to Man-In-The-Middle attacks

**Comment by danmoore2205** [comment]
Thanks for the info @timothyrobb

**Comment by joshjordan** [comment]
Resolved.

**Comment by matiasmasca** [comment]
This is happening again today.
