### ISSUE TITLE
Feature request - support a dark mode on rails assets.org

### ISSUE THREAD

**Issue by CloCkWeRX** [tenex/rails-assets#479]
Reproduce steps:

* Put dark mode on at the OS level
* Visit https://rails-assets.org/

Expected:
A darker theme is applied, as per 
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by hut8** [comment]
We have no budget for effort on new features. If you submit a PR, we will likely merge it. New projects should not be using rails-assets.org because bower is deprecated and rails-assets is built on bower. Almost all of our traffic is not to the front-end UI but to the asset building and serving parts.

**Comment by hut8** [comment]
@CloCkWeRX if you want to add a PR, that's cool, but I'm closing this for now.
