### ISSUE TITLE
Please explain advantages ?

### ISSUE THREAD

**Issue by fahim-patel** [tenex/rails-assets#68]
I have studied your site and I like below statement:-

"It automatically converts the packaged components into gems that are easily droppable into your asset pipeline and stay up to date."

Please can you list advantages that would force me to implement rails-assets.

Thanks

Best Regards
Fahim Babar Patel

**Comment by sheerun** [comment]
I guess you ask for advantages compared to using bower/grunt directly, because managing assets as dependencies instead of putting js/css files into vendor/assets is pretty obvious for everyone.

Basically you can use Rails stack with Bower components (manage dependencies with bundler, use sprocket's assets pipeline, use CSS helpers like image-url or asset-url or @include or image_tag, automatically precompile with component dependencies, concatente, compress, handle http cache flushing) and have no dependency on JS environment (neither execjs nor bower/grunt is not required for asset precompilation). Additionally rails-assets rewrites url() calls in stylesheets to proper image-url() which normally you need to do manually to make your stylesheets working.

Does it answer your question?

**Comment by Olgagr** [comment]
I think this guy made a quite good job to describe what problem Rails Assets tries to resolve:

https://www.codefellows.org/blogs/five-ways-to-manage-front-end-assets-in-rails

**Comment by fahim-patel** [comment]
@sheerun :+1:  @Olgagr :+1:  .

Thanks for quick response. I will go through above URL and get back to you.

**Comment by fahim-patel** [comment]
@sheerun :+1:
