### ISSUE TITLE
Problems when compiling assets

### ISSUE THREAD

**Issue by onordgren** [tenex/rails-assets#87]
Hello,

I ran into some problems when trying to compile my assets with 'rails-assets-angular' in my gemfile. The compiling stops because bower-angular includes gzip files as seen here https://github.com/angular/bower-angular. 

The error I get is .../angular.min.js.gzip has a invalid UTF-8 byte sequence 

Any thoughts?

**Comment by sheerun** [comment]
This is the same issue as #81 

I think we need to create either whitelist or blacklist of allowed extensions. Stay tuned.

**Comment by sheerun** [comment]
@onordgren Could you post your Gemfile.lock ? I'm not sure why sprockets wants to compile .gzip file.

**Comment by sheerun** [comment]
I opened an issue on sprockets: sstephenson/sprockets#519

**Comment by seantanly** [comment]
:+1: 

This is a major blocker. Hopefully this gets resolved fast.

**Comment by seantanly** [comment]
@sheerun I did some investigation on my own. This issue seems more than just reading in of binary data.

Sprockets is reading in files that are not meant to be precompiled. Even if we make Sprockets::Utils handle binary data, it will still choke on .map files because there isn't a preprocessor for it.

The solution could be making sure only files that are to be processed by sprockets are passed along.

Monkey patching this in allows me to successfully precompile angular

```
module Sprockets
  module SkipFiles
    def evaluate(path, options = {})
      if path.to_s[/\.(gzip|map)$/]
        STDERR.puts "#{path}: skipped"
        ''
      else
        STDERR.puts "#{path}: super"
        super
      end
    end
  end
end

Sprockets::Context.send(:prepend, Sprockets::SkipFiles)
```

**Comment by onordgren** [comment]
@sheerun sorry about the late reply. 

Here is a gist of my Gemfile.lock https://gist.github.com/onordgren/8335446

@seantan Where should I put the monkey patch?
I tried putting it in config/initializers but I got an error when trying to precompile. There error was
- undefined method `prepend' for Sprockets::Context:Class

**Comment by seantanly** [comment]
Prepend is a method only available from ruby 2.0+. I used it to illustrate
the point. If you need it urgently for earlier version of ruby, I'll whip
up a quick hack for you

**Comment by sheerun** [comment]
I'm removing all .gzip, .map and .nuspec files from compiled components. This should be temporary fix. I'm performing full rebuild, it should take about 1h.

**Comment by onordgren** [comment]
I see. Not that urgent so I can wait for sprockets to fix it. Thanks anyway :)

## 

Otto Nordgren
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by sheerun** [comment]
@onordgren @seantan All gems has been rebuilt. Could you confirm if it's working for you?

You may need to remove local gems: `gem list | grep rails-assets | cut -d ' ' -f 1 | xargs gem uninstall`

**Comment by onordgren** [comment]
@sheerun Seems to be working locally for me. But when i try to bundle on my production server i get the following error

 *\* [out :: 109.74.9.50] Net::HTTPNotFound: File not found:
 *\* [out :: 109.74.9.50] /quick/Marshal.4.8/rails-assets-Backbone.ModelBinder-0.1.2.gemspec.rz

Not sure if the error is on my end or yours though.

**Comment by sheerun** [comment]
Ouch. This is first entry from specs.4.8 file on Rails Assets. It's strange because http://rails-assets.org/quick/Marshal.4.8/rails-assets-Backbone.ModelBinder-0.1.2.gemspec.rz exists. Maybe it was temporary issue due to reindex? Does it happen again? What happend if you `gem list | grep rails-assets | cut -d ' ' -f 1 | xargs gem uninstall` on production?

**Comment by onordgren** [comment]
Tried again and now it seems to work on production as well. Couldn't remove the gems manually but i deleted the shared/bundle folder and re-installed all the gems.

Thanks for the fix and the quick replies!

**Comment by seantanly** [comment]
@sheerun Thanks for the quick fix, it's working for me.
