### ISSUE TITLE
Make components dependent on precompiler gems 

### ISSUE THREAD

**Issue by sheerun** [tenex/rails-assets#91]
- all assets: `sprockets`
- with `.coffee`: `coffee-script >= 2.2.0` (to use execjs, not therubyracer)
- with `.sass`, `.scss`: `sass >= 3.2.0` (just like `sass-rails`)
- with `.less`:  probably `less`, but it uses `therubyracer` :(
- with `.styl`: `stylus >= 1.0.0`

I think we should convert all `.css` files to `.scss` to prevent `css.erb` and ruby helpers.

Any objections or different / additional engines proposals?

ping @teamon @porada

**Comment by porada** [comment]
Where is the line that we shouldn’t cross with this project? I’m asking, because from time to time I feel like we’re overthinking stuff—and this is the exemplary issue.

Well-defined packages work just fine with both Bower and Rails Assets. Yet we even fix the fixable (no `main` scripts, Sass files, etc.) that Bower doesn’t enforce nor validate.

When do we just say “no” and leave the responsibility for all what’s broken to package authors, users, and the community capable of fixing individual packages when necessary? We should keep in mind Rails Assets will never be bulletproof, because there’s third-party code involved.

People report issues—which is great—but some of them are not our itch to scratch. We can always [guide them](http://en.wiktionary.org/wiki/give_a_man_a_fish_and_you_feed_him_for_a_day._Teach_a_man_to_fish_and_you_feed_him_for_a_lifetime) how to make particular fixes, and only improve Rails Assets when it actually requires some tweaking.

**Comment by sheerun** [comment]
This is not about broken bower packages, but broken sprockets integration. For now our packages won't work if you don't define `sass-rails` in `Gemfile`. The same goes for any other precompiled filetype.

**Comment by sheerun** [comment]
Nice list of extension-gem pairs: https://github.com/rtomayko/tilt

**Comment by porada** [comment]
People who use certain packages should learn about their depenedencies. This shouldn’t be done automatically to prevent the usage of multiple precompilers.

**Comment by Peeja** [comment]
What does the failure look like right now if you don't explicitly include a precompiler in your Gemfile? Should rails-assets provide a fallback which fails with a more informative and actionable error message?

**Comment by sheerun** [comment]
I think it won't be implemented because some packages can contain both .less, .scss, .css etc. files and we don't want to force things like therubyracer or stylus to be a depdendency if you don't use them.
